#app_api_doc:
#    resource: './routes/api/nelmio'
#    type: directory
app_api_auth_login:
    resource: './routes/api/auth'
    type: directory
app_api_auth_logout:
  resource: ../src/Module/System/Presentation/API/Controller/
  type: attribute
app_api:
    resource: ../src/Module/Company/Presentation/API/Controller/
    type: attribute
app_api_note:
    resource: ../src/Module/Note/Presentation/API/Controller/
    type: attribute
