imports:
    - { resource: './services/main.yaml' }
    - { resource: './services/module/company/company.yaml' }
    - { resource: './services/module/company/department.yaml' }
    - { resource: './services/module/company/employee.yaml' }
    - { resource: './services/module/company/role.yaml' }
    - { resource: './services/module/company/position.yaml' }
    - { resource: './services/module/company/industry.yaml' }
    - { resource: './services/module/company/contract_type.yaml' }
    - { resource: './services/module/system/file.yaml' }
    - { resource: './services/module/system/log.yaml' }
    - { resource: './services/module/system/import.yaml' }
    - { resource: './services/module/system/import_log.yaml' }
    - { resource: './services/module/system/email.yaml' }
    - { resource: './services/module/system/sms.yaml' }
    - { resource: './services/module/note/note.yaml' }
