name: Symfony CI

on:
  push:
    branches:
      - "master"
      - "feature/**"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      APP_ENV: test
      JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
      JWT_SECRET_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
      DATABASE_URL: "mysql://root:root_password@service-company-db:3306/service_company?serverVersion=8.0&charset=utf8mb4"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start all containers
        run: docker compose up -d --build

      - name: Wait for MySQL to be healthy
        run: |
          docker compose exec -T service-company-db \
            bash -c 'until mysqladmin ping -h localhost --silent; do sleep 1; done'

      - name: Install dependencies
        run: docker compose exec -T service-company composer install

      - name: Show current dir
        run: pwd

      - name: Create JWT directory
        run: mkdir -p src/config/jwt

      - name: Write JWT keys
        run: |
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > src/config/jwt/private.pem
          echo "${{ secrets.JWT_PUBLIC_KEY }}" > src/config/jwt/public.pem
          chmod 600 src/config/jwt/private.pem src/config/jwt/public.pem

      - name: Debug JWT files
        run: ls -la src/config/jwt

      - name: Run migrations on main DB (dev DB)
        run: docker compose exec -T service-company php bin/console doctrine:migrations:migrate --no-interaction --env=dev

      - name: Initialize system data (dev DB)
        run: |
          docker compose exec -T service-company php bin/console app:initialize-system-default-data --env=dev
          docker compose exec -T service-company php bin/console app:initialize-system-fake-data --env=dev

      - name: Create test DB
        run: docker compose exec -T service-company php bin/console doctrine:database:create --env=test

      - name: Run migrations on test database
        run: docker compose exec -T service-company php bin/console doctrine:migrations:migrate --env=test --no-interaction

      - name: Run PHPUnit tests
        run: docker compose exec -T service-company php bin/phpunit